"""The generic/messy-layout paths: row splitting, table sniffing, text rows."""
import pytest

from statement_analyzer import load_statement
from statement_analyzer.parsers.generic import (
    KNOWN_HEADERS,
    ROW_PATTERNS,
    align_and_split_table,
    find_transaction_table,
    remove_blank_first2rows,
    split_by_structure,
    split_transaction_row,
)

# One row per original pattern shape. Every one of these used to be handled by
# the old split_transaction_row and must keep working.
ROWS = {
    "datetime + value date + debit/credit": (
        "1 02 May 2025 10:11:12 : 3 02 May 2025 TRF FRM JOHN TO JANE -- 5,000.00 25,000.00 NIP REF12345",
        {"date": "02 May 2025 10:11:12", "value_date": "02 May 2025", "credit": "5,000.00", "balance": "25,000.00"},
    ),
    "narration before value date": (
        "02 May 2025 10:11 POS PURCHASE SHOPRITE 02 May 2025 2,500.00 -- 22,500.00 POS REF999",
        {"narration": "POS PURCHASE SHOPRITE", "debit": "2,500.00", "balance": "22,500.00", "channel": "POS"},
    ),
    "optional index + value date": (
        "02 May 2025 12 02 May 2025 TRANSFER TO ADE -1,000.00 21,500.00 mobile REF00123",
        {"narration": "TRANSFER TO ADE", "amount": "-1,000.00", "balance": "21,500.00", "reference": "REF00123"},
    ),
    "trailing point count": (
        "2025 May 02 10: TRANSFER TO ADE 02 May 2025 -1,000.00 21,500.00 mobile ABC123 4 point",
        {"date": "2025 May 02 10:", "amount": "-1,000.00", "reference": "ABC123"},
    ),
    "reference before value date": (
        "2025 May 02 10: ABC123 02 May 2025 TRANSFER TO ADE point -1,000.00 21,500.00 mobile 4 5",
        {"reference": "ABC123", "narration": "TRANSFER TO ADE", "balance": "21,500.00"},
    ),
    "description first": (
        "TRANSFER TO ADE 2025 May 02 10:11:12 02 May 2025 -1,000.00 21,500.00 mobile 100000000000001",
        {"narration": "TRANSFER TO ADE", "date": "2025 May 02 10:11:12", "reference": "100000000000001"},
    ),
    "datetime first": (
        "2025 May 02 10:11 TRANSFER TO ADE 02 May 2025 -1,000.00 21,500.00 mobile 100000000000001",
        {"date": "2025 May 02 10:11", "amount": "-1,000.00", "balance": "21,500.00"},
    ),
    "dashed balance": (
        "2025 May 02 10:11 02 May 2025 TRANSFER TO ADE -1,000.00 -- mobile REF123",
        {"amount": "-1,000.00", "channel": "mobile"},           # '--' balance dropped, not kept as text
    ),
    "index + value date only": (
        "12 02 May 2025 TRANSFER TO ADE -1,000.00 21,500.00 mobile REF123",
        {"value_date": "02 May 2025", "amount": "-1,000.00", "channel": "mobile"},
    ),
    "narration first with debit/credit": (
        "TRF FRM JOHN 02 May 2025 10:11:12 02 May 2025 -- 5,000.00 25,000.00 NIP REF12345",
        {"narration": "TRF FRM JOHN", "credit": "5,000.00", "balance": "25,000.00"},
    ),
}


@pytest.mark.parametrize("text, expected", list(ROWS.values()), ids=list(ROWS))
def test_every_original_pattern_still_splits(text, expected):
    record = split_transaction_row(text)
    assert record is not None
    for key, value in expected.items():
        assert record.get(key) == value, key
    assert "--" not in record.values()


def test_dashed_balance_is_not_kept():
    record = split_transaction_row("2025 May 02 10:11 02 May 2025 TRANSFER TO ADE -1,000.00 -- mobile REF123")
    assert "balance" not in record


def test_patterns_are_precompiled_once():
    assert ROW_PATTERNS and all(hasattr(p, "match") for p in ROW_PATTERNS)


# ----------------------------------------------------- structural fallback
@pytest.mark.parametrize("text, expected", [
    ("05/07/2024 Cash deposit at branch counter 15,000.00 315,000.00",
     {"date": "05/07/2024", "narration": "Cash deposit at branch counter",
      "amount": "15,000.00", "balance": "315,000.00"}),
    ("2024-07-05 2024-07-06 SALARY PAYMENT JULY -- 450,000.00 765,000.00",
     {"value_date": "2024-07-06", "credit": "450,000.00", "balance": "765,000.00"}),
    ("12-Jan-24 USSD transfer 1,000.00 2,000.00 45,000.00 mobile ABC12345",
     {"date": "12-Jan-24", "channel": "mobile", "reference": "ABC12345"}),
])
def test_structural_fallback_handles_unknown_shapes(text, expected):
    record = split_by_structure(" ".join(text.split()))
    assert record is not None
    for key, value in expected.items():
        assert record.get(key) == value, key


def test_structural_fallback_rejects_junk():
    assert split_by_structure("Page 2 of 5") is None
    assert split_by_structure("Generated by the bank on request") is None
    assert split_transaction_row("") is None


# ------------------------------------------------------- table row helpers
def test_remove_blank_first2rows():
    assert remove_blank_first2rows(["", "", "Date", "Details", "", None]) == ["Date", "Details"]
    assert remove_blank_first2rows(["", "Date", "Amount"]) == ["Date", "Amount"]
    assert remove_blank_first2rows([]) == []


def test_known_header_is_found_and_rows_follow():
    header = KNOWN_HEADERS[0]
    table = [["ACCOUNT STATEMENT"], header,
             ["02 May 2025", "POS SHOPRITE", "REF1", "02 May 2025", "2,500.00", "", "22,500.00"]]
    found, rows = find_transaction_table([table])
    assert found == header
    assert len(rows) == 2                       # header + one transaction


def test_summary_block_is_not_mistaken_for_a_header():
    table = [["Print. Date", "Balance"], ["01/01/2024", "10,000.00"]]
    found, _ = find_transaction_table([table])
    assert found is None


def test_account_statement_title_then_real_header():
    table = [["Account Statement", "for May"],
             ["TXN DATE", "VAL DATE", "REMARKS", "DEBIT", "CREDIT", "BALANCE"],
             ["02/05/2025", "02/05/2025", "POS", "2,500.00", "", "22,500.00"]]
    found, rows = find_transaction_table([table])
    assert found[0] == "TXN DATE" and len(rows) == 2


def test_merged_single_cell_rows_are_split():
    header = ["Date", "Transaction Details", "Reference", "Value Date", "Withdrawals", "Lodgements", "Balance"]
    table = [
        [None, "02 May 2025 10:11 POS PURCHASE SHOPRITE 02 May 2025 2,500.00 -- 22,500.00 POS REF999", None],
        ["02 May 2025", "Transfer in", "REF2", "02 May 2025", "", "5,000.00", "27,500.00"],
    ]
    records = align_and_split_table(table, header)
    assert len(records) == 2
    assert records[0]["narration"] == "POS PURCHASE SHOPRITE"
    assert records[0]["debit"] == "2,500.00"
    assert records[1]["credit"] == "5,000.00" and records[1]["balance"] == "27,500.00"


def test_keystone_style_single_cell_header():
    header = ["Trans Date Value Date Narration Amount Balance\nDate extra"]
    table = [["02 May 2025", "02 May 2025", "POS SHOPRITE", "2,500.00", "22,500.00"]]
    records = align_and_split_table(table, header)
    assert records and records[0]["narration"] == "POS SHOPRITE"


def test_row_with_unmapped_header_falls_back_to_the_splitter():
    # Header the synonym list doesn't know: mapping yields nothing, so the row
    # text is re-tried through the splitters instead of being dropped.
    header = ["Col1", "Col2", "Col3"]
    table = [["05/07/2024", "Cash deposit at counter", "15,000.00 315,000.00"]]
    records = align_and_split_table(table, header)
    assert records and records[0]["balance"] == "315,000.00"


# -------------------------------------------------------------- end to end
def _messy_text_pdf(path):
    """No ruled table, no readable header — only the row shapes give it away."""
    from reportlab.lib.pagesizes import A4
    from reportlab.pdfgen import canvas

    c = canvas.Canvas(str(path), pagesize=A4)
    lines = [
        "SOME MICROFINANCE BANK",
        "Statement of account for ADEOLA SAMUEL",
        "Opening Balance: 22,500.00",
        "2025 May 02 10:11 TRANSFER TO ADE 02 May 2025 -1,000.00 21,500.00 mobile 100000000000001",
        "2025 May 03 09:00 TRF FRM JOHN 03 May 2025 +5,000.00 26,500.00 mobile 100000000000002",
        "Page 1 of 1",
        "2025 May 04 12:30 AIRTIME MTN 04 May 2025 -500.00 26,000.00 mobile 100000000000003",
    ]
    y = 800
    for ln in lines:
        c.drawString(40, y, ln)
        y -= 18
    c.save()


def test_messy_text_only_pdf_is_extracted():
    pytest.importorskip("reportlab")
    import tempfile
    from pathlib import Path

    with tempfile.TemporaryDirectory() as tmp:
        pdf = Path(tmp) / "messy.pdf"
        _messy_text_pdf(pdf)
        s = load_statement(pdf)

    assert s.source == "pdf:Generic (text rows)"
    assert len(s.transactions) == 3
    assert s.transactions["direction"].tolist() == ["debit", "credit", "debit"]
    assert s.quality.reconciliation_rate == 1.0
    assert s.opening_balance == 22_500
