from analyzer.registry import ProcessorRegistry
from analyzer.processors import *

ProcessorRegistry.register(MoniepointProcessor)
ProcessorRegistry.register(PtrustProcessor)
ProcessorRegistry.register(SterlingProcessor)
ProcessorRegistry.register(TAJProcessor)
ProcessorRegistry.register(PalmPayProcessor)
ProcessorRegistry.register(ZenithProcessor)
ProcessorRegistry.register(FidelityProcessor)
ProcessorRegistry.register(OpayProcessor)
ProcessorRegistry.register(MultipleProcessor)
